stages:
    - build_base
    - build_base-node8

build_base_image:
    stage: build_base
    image: docker:stable
    script:
        - IMAGENAME=base
        - RELEASEDATE=$(date)
        - docker build --no-cache -t "${IMAGENAME}" -f base/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - docker push daedalusproject/"${IMAGENAME}"
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"

build_base-node8_image:
    stage: build_base-node8
    image: docker:stable
    script:
        - IMAGENAME=base8
        - RELEASEDATE=$(date)
        - docker build --no-cache -t "${IMAGENAME}" -f base-node8/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - docker push daedalusproject/"${IMAGENAME}"
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"
