stages:
    - build_base
    - build_base_node8
    - build_base_nginx_light
    - build_base_hugo

build_base_image:
    stage: build_base
    image: docker:stable
    script:
        - IMAGENAME=base
        - RELEASEDATE=$(date)
        - mkdir timestamp
        - date +%Y%m%d%H%M > timestamp/timestampfile
        - docker build --network=host --no-cache -t "${IMAGENAME}" -f base/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - docker push daedalusproject/"${IMAGENAME}"
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"
    artifacts:
        paths:
        - timestamp
        expire_in: 15 minutes

build_base_node8_image:
    stage: build_base_node8
    image: docker:stable
    script:
        - IMAGENAME=base_node8
        - RELEASEDATE=$(date)
        - docker build --network=host --no-cache -t "${IMAGENAME}" -f "${IMAGENAME}"/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - docker push daedalusproject/"${IMAGENAME}"
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"
    dependencies:
    - build_base_image

build_base_nginx_light_image:
    stage: build_base_nginx_light
    image: docker:stable
    script:
        - IMAGENAME=base_nginx_light
        - RELEASEDATE=$(date)
        - docker build --network=host --no-cache -t "${IMAGENAME}" -f "${IMAGENAME}"/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - docker push daedalusproject/"${IMAGENAME}"
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"
    dependencies:
    - build_base_image

build_base_hugo_image:
    stage: build_base_hugo
    image: docker:stable
    script:
        - IMAGENAME=base_hugo
        - RELEASEDATE=$(date)
        - DATESTRING=$(cat timestamp/timestampfile)
        - BASEIMAGE=$(echo -e $(grep "FROM " "${IMAGENAME}"/Dockerfile |sed 's/:.*//' | sed 's/FROM //'))
        -  if [ "${CI_COMMIT_REF_NAME}" == "master" ]; then BASEIMAGE="$BASEIMAGE:$DATESTRING"; else BASEIMAGE="$BASEIMAGE:latest"; fi
        - echo $BASEIMAGE
        - docker build --network=host --no-cache -t "${IMAGENAME}" --build-arg BASE_IMAGE=$BASEIMAGE -f "${IMAGENAME}"/Dockerfile .
        - docker login --username "${DOCKERHUBUSER}" --password "${DOCKERHUBPASSWORD}"
        - docker create --name="${IMAGENAME}" -i "${IMAGENAME}"
        - if [ "${CI_COMMIT_REF_NAME}" == "6-hugo_base" ]; then docker tag "${IMAGENAME}" daedalusproject/"${IMAGENAME}":"${DATESTRING}"; fi
        - docker tag "${IMAGENAME}" daedalusproject/"${IMAGENAME}":latest
        - docker commit -m "$RELEASEDATE" -a "Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>" "${IMAGENAME}" daedalusproject/"${IMAGENAME}"
        - if [ "${CI_COMMIT_REF_NAME}" == "6-hugo_base" ]; then docker push daedalusproject/"${IMAGENAME}":"${DATESTRING}"; fi
        - docker push daedalusproject/"${IMAGENAME}":latest
        - docker stop "${IMAGENAME}"
        - docker rm "${IMAGENAME}"
        - docker rmi "${IMAGENAME}"
    dependencies:
    - build_base_image
